<?php
/**
 * Template Name: Terms of Service
 * Template for Terms of Service page
 *
 * @package SGS_Theme
 */

get_header();
?>

<main id="main" class="site-main legal-page">
    
    <!-- Page Header -->
    <section class="legal-page-header">
        <div class="container">
            <div class="legal-header-content">
                <h1 class="page-title">Terms of Service</h1>
                <p class="page-subtitle">Last updated:July 16, 2024;</p>
            </div>
        </div>
    </section>

    <!-- Terms of Service Content -->
    <section class="legal-content-section">
        <div class="container">
            <div class="legal-content">
                <div class="legal-section">
                    <p>THIS DOCUMENT CONTAINS VERY IMPORTANT INFORMATION REGARDING YOUR RIGHTS AND OBLIGATIONS, AS WELL AS CONDITIONS, LIMITATIONS, AND EXCLUSIONS THAT MIGHT APPLY TO YOU. THIS DOCUMENT GOVERNS YOUR ACCESS TO AND USE OF PROVIDER’S SERVICES. PLEASE READ IT CAREFULLY.</p>
                    <p>BY PLACING AN ORDER FOR SERVICES FROM PROVIDER, CUSTOMER AGREES AND AFFIRMS THAT BOTH CUSTOMER AND THE INDIVIDUAL INDICATING SUCH ACCEPTANCE OR EXECUTING SUCH ORDER FORM HAS THE LEGAL AUTHORITY TO BIND ANY SUCH CUSTOMER TO THESE TERMS AND CONDITIONS.</p>
                    <p>CUSTOMER MAY NOT ORDER OR OBTAIN SERVICES FROM PROVIDER IF CUSTOMER (A) DOES NOT AGREE TO THESE TERMS, (B) IS NOT THE OLDER OF (i) AT LEAST 18 YEARS OF AGE OR (ii) LEGAL AGE TO FORM A BINDING CONTRACT WITH PROVIDER, OR (C) ARE PROHIBITED FROM ACCESSING OR USING THE SERVICES OR ANY OF PROVIDER’S GOODS OR SERVICES BY APPLICABLE LAW.</p>
                </div>

                <div class="legal-section">
                    <p>These Terms of Service (these “Terms”) and accompanying Order Form accompanying or referencing these Terms comprise the entire agreement (the “Agreement”) between Grant Compliance Solutions, LLC, dba Smart Grant Solutions, a Pennsylvania limited liability company with offices located at 302 Marilyn Drive, New Castle, PA 16105 (“Provider” “us”, “we”, or “our” as the context may require), and the person or entity identified on the Order Form (“Customer”) to license Provider’s services described on the Order Form (the “Services”), effective as of the date listed on the Order Form (the “Effective Date”). “Order Form” means any document, print or digital, provided by Provider related to providing the Services, including but not limited to quotations, invoices, documents confirming, acknowledging or accepting an order and shipping documents. Provider and Customer may be referred to herein collectively as the “Parties” or individually as a “Party.”</p>
                    <p>This Agreement supersedes all prior or contemporaneous understandings, agreements, negotiations, representations and warranties, and communications, both written and oral. In the event of any conflict between these Terms and the Order Form, these Terms shall govern, unless the Order Form expressly states that the terms and conditions of the Order Form shall control. These Terms prevail over any of Customer’s general terms and conditions regardless of whether or when Customer has submitted its request for proposal, order, or such terms. Provision of Services to Customer does not constitute acceptance of any of Customer’s terms and conditions and does not serve to modify or amend these Terms. If the parties have signed a contract applicable to the Services, the terms of such contract shall prevail to the extent they are inconsistent with these Terms.</p>
                    <p>These Terms are subject to change by Provider without prior written notice at any time, in our sole discretion. Any changes to the Terms will be in effect as of the “Last Updated Date” referenced on the Site. Customer should review these Terms before purchasing or using the Services. Customer’s continued use of the Services after the “Last Updated Date” will constitute your acceptance of and agreement to such changes.</p>
                    <p>These Terms are an integral part of the Website Terms of Use that apply generally to the use of our Services. Customer should also carefully review our Privacy Policy before placing an order for the Services.</p>
                </div>

                <div class="legal-section">
                    <h2>1. Access and Use.</h2>
                    <p>(a) Provision of Access. Subject to the terms and conditions of this Agreement, and conditioned on Customer’s payment of all Fees and compliance with all other terms and conditions of this Agreement, Provider hereby grants Customer a revocable, non-exclusive, non-transferable non-sublicensable, limited right during the Term to: (i) access and use the Services solely for Customer’s internal business purposes by employees of Customer that Customer permits to access and use the Services and/or Documentation (“Authorized Users”); and (ii) use Provider’s user manuals, handbooks, and guides relating to the Services by Authorized Users provided by Provider to Customer either electronically or in hard copy form (the “Documentation”) solely for Customer’s internal business purposes in connection with Customer’s use of the Services, in each of (i) and (ii), in accordance with the terms and conditions of this Agreement.</p>
                    <p>(b) Use Restrictions. Customer shall not use the Services or Documentation for any purposes beyond the scope of the access granted in this Agreement. Except as otherwise set forth in this Agreement, Customer shall not at any time, directly or indirectly, and shall not permit any Authorized Users to: (i) copy, modify, or create derivative works of the Services or Documentation, in whole or in part; (ii) rent, lease, lend, sell, license, sublicense, assign, distribute, publish, transfer, or otherwise make available the Services or Documentation; (iii) reverse engineer, disassemble, decompile, decode, adapt, or otherwise attempt to derive or gain access to any software component of the Services, in whole or in part; (iv) remove any proprietary notices from the Services or Documentation; or (v) use the Services or Documentation in any manner or for any purpose that infringes, misappropriates, or otherwise violates any intellectual property right or other right of any person, or that violates any applicable law.</p>
                    <p>(c) Reservation of Rights. Provider reserves all rights not expressly granted to Customer in this Agreement. Except for the limited rights and licenses expressly granted under this Agreement, nothing in this Agreement grants, by implication, waiver, estoppel, or otherwise, to Customer or any third-party, any intellectual property rights or other right, title, or interest in or to the Services, the Documentation, or any and all intellectual property provided to Customer or any Authorized User in connection with the foregoing (“Provider IP”).</p>
                    <p>(d) Suspension. Notwithstanding anything to the contrary in this Agreement, Provider may temporarily suspend Customer’s and any Authorized User’s access to any portion or all of the Services if: (i) Provider reasonably determines that (A) there is a threat or attack on any of the Provider IP; (B) Customer’s or any Authorized User’s use of the Provider IP disrupts or poses a security risk to the Provider IP or to any other customer or vendor of Provider; (C) Customer, or any Authorized User, is using the Provider IP for fraudulent or illegal activities; (D) subject to applicable law, Customer has ceased to continue its business in the ordinary course, made an assignment for the benefit of creditors or similar disposition of its assets, or become the subject of any bankruptcy, reorganization, liquidation, dissolution, or similar proceeding; or (E) Provider’s provision of the Services to Customer or any Authorized User is prohibited by applicable law; (ii) any vendor of Provider has suspended or terminated Provider’s access to or use of any third-party services or products required to enable Customer to access the Services; or (iii) Customer fails to make any payment when due (any such suspension described in subclause (i), (ii), or (iii), a “Service Suspension”). Provider shall use commercially reasonable efforts to provide written notice of any Service Suspension to Customer and to provide updates regarding resumption of access to the Services following any Service Suspension. Provider shall use commercially reasonable efforts to resume providing access to the Services as soon as reasonably possible after the event giving rise to the Service Suspension is cured. Provider will have no liability for any damage, liabilities, losses (including any loss of data or profits), or any other consequences that Customer or any Authorized User may incur as a result of a Service Suspension.</p>
                    <p>(e) Changes. Provider reserves the right, in its sole discretion, to make any changes to the Services and Documentation that it deems necessary or useful to: (i) maintain or enhance: (A) the quality or delivery of Provider’s services to its customers; (B) the competitive strength of or market for Provider’s services; (C) the Services’ cost efficiency or performance; or (ii) to comply with applicable law.</p>
                </div>

                <div class="legal-section">
                    <h2>2. Customer Responsibilities.</h2>
                    <p>The Services may not be used for unlawful, fraudulent, offensive, or obscene activity, and Customer shall comply with all terms and conditions of this Agreement, all applicable laws, rules, and regulations when accessing or using the Services. Customer is responsible and liable for all uses of the Services and Documentation resulting from access provided by Customer, directly or indirectly, whether such access or use is permitted by or in violation of this Agreement. Without limiting the foregoing, Customer is responsible for all acts and omissions of Authorized Users, and any act or omission by an Authorized User that would constitute a breach of this Agreement if taken by Customer will be deemed a breach of this Agreement by Customer. Customer shall take reasonable efforts to make all Authorized Users aware of this Agreement’s provisions as applicable to such Authorized User’s use of the Software, and shall cause Authorized Users to comply with such provisions. Customer shall provide Provider with such access to Customer’s premises and information technology infrastructure, including computers, software, hardware, databases, electronic systems (including database management systems), and networks, whether operated directly by Customer or through the use of third-party service as is necessary or useful to enable Provider to exercise its rights and perform its obligations under and in connection with this Agreement. Customer shall provide all cooperation and assistance as Provider may reasonably request.</p>
                </div>

                <div class="legal-section">
                    <h2>3. Support.</h2>
                    <p>Provider has no obligation under this Agreement to provide support, maintenance, upgrades, modifications, or new releases of the Services or Documentation to Customer. Subject to the terms and conditions of this Agreement, and conditioned on Customer’s compliance therewith, during the Term, Provider may, at Provider’s option, use commercially reasonable efforts to provide customer support services on weekdays (excluding public holidays) between the hours of 8 AM and 5 PM Eastern Time to support Customer’s use of the Services during the Term in accordance with the terms and conditions of this Agreement (“Support Services”). Hours of Support Services are subject to change from time to time at Provider’s sole discretion.</p>
                </div>

                <div class="legal-section">
                    <h2>4. Data Backup.</h2>
                    <p>The Services do not replace the need for Customer to maintain regular data backups or redundant data archives. PROVIDER HAS NO OBLIGATION OR LIABILITY FOR ANY LOSS, ALTERATION, DESTRUCTION, DAMAGE, CORRUPTION, OR RECOVERY OF CUSTOMER DATA.</p>
                </div>

                <div class="legal-section">
                    <h2>5. Professional Services.</h2>
                    <p>Customer may purchase Professional Services by executing an Order Form describing such professional services (“Professional Services”). The terms and conditions of this Agreement will apply to Professional Services purchased from Provider. Professional Services are non-cancellable and all fees paid for Professional Services are non-refundable. Customer may also purchase Professional Services directly from third-party partners referred by Provider (“Third-Party Professional Services”). Third-Party Professional Services are governed solely by any agreements between Customer and such third-party. Partner does not warrant or support Third-Party Professional Services.</p>
                </div>

                <div class="legal-section">
                    <h2>6. Fees and Payment.</h2>
                    <p>(a) Fees. Customer shall pay Provider the fees (“Fees”) as set forth in the Order Form without offset or deduction. Customer shall make all payments hereunder in US dollars on or before the due date set forth in the Order Form. If Customer fails to make any payment when due, without limiting Provider’s other rights and remedies: (i) Provider may charge interest on the past due amount at the rate of 1.5% per month calculated daily and compounded monthly or, if lower, the highest rate permitted under applicable law; (ii) Customer shall reimburse Provider for all costs incurred by Provider in collecting any late payments or interest, including attorneys’ fees, court costs, and collection agency fees; and (iii) if such failure continues for 30 days or more, Provider may suspend Customer’s and its Authorized Users’ access to any portion or all of the Services until such amounts are paid in full. Provider may increase Fees for any contract year after the first contract year of the Initial Term, including any contract year of any Renewal Term, by providing written notice to Customer at least 60 calendar days prior to the commencement of that contract year, and the Order Form will be deemed amended accordingly. All Fees and other amounts payable by Customer under this Agreement are exclusive of taxes and similar assessments. Customer is responsible for all sales, use, and excise taxes, and any other similar taxes, duties, and charges of any kind imposed by any federal, state, or local governmental or regulatory authority on any amounts payable by Customer hereunder, other than any taxes imposed on Provider’s income.</p>
                    <p>(b) Payment. Payment will be made by credit card or ACH. Provider will provide a secure link whereby Customer will enter the appropriate credit card or bank information. Customer authorizes Provider to charge Customer credit card or bank account for all fees billable and due in accordance with this Section of the Agreement. Customer authorizes Provider to use a third-party to process payments, and consents to the disclosure of payment information to such third-party. Provider will keep contact information, billing information, credit card or bank account information up to date.</p>
                </div>

                <div class="legal-section">
                    <h2>7. Confidential Information.</h2>
                    <p>From time to time during the Term, Provider may disclose or make available to Customer information about its business affairs, products, confidential intellectual property, trade secrets, third-party confidential information, and other sensitive or proprietary information, whether orally or in written, electronic, or other form or media, and whether or not marked, designated, or otherwise identified as “confidential” (collectively, “Confidential Information”). Confidential Information does not include information that, at the time of disclosure is: (a) in the public domain; (b) known to the receiving Party at the time of disclosure; (c) rightfully obtained by the receiving Party on a non-confidential basis from a third-party; or (d) independently developed by the receiving Party. The receiving Party shall not disclose the disclosing Party’s Confidential Information to any person or entity, except to the receiving Party’s employees who have a need to know the Confidential Information for the receiving Party to exercise its rights or perform its obligations hereunder. Notwithstanding the foregoing, each Party may disclose Confidential Information to the limited extent required (i) in order to comply with the order of a court or other governmental body, or as otherwise necessary to comply with applicable law, provided that the Party making the disclosure pursuant to the order shall first have given written notice to the other Party and made a reasonable effort to obtain a protective order; or (ii) to establish a Party’s rights under this Agreement, including to make required court filings. On the expiration or termination of the Agreement, the receiving Party shall promptly return to the disclosing Party all copies, whether in written, electronic, or other form or media, of the disclosing Party’s Confidential Information, or destroy all such copies and certify in writing to the disclosing Party that such Confidential Information has been destroyed. Each Party’s obligations of non-disclosure with regard to Confidential Information are effective as of the Effective Date and will expire five years from the date first disclosed to the receiving Party; provided, however, with respect to any Confidential Information that constitutes a trade secret (as determined under applicable law), such obligations of non-disclosure will survive the termination or expiration of this Agreement for as long as such Confidential Information remains subject to trade secret protection under applicable law.</p>
                </div>

                <div class="legal-section">
                    <h2>8. Privacy Policy.</h2>
                    <p>Provider complies with its privacy policy in providing the Services. The Privacy Policy is subject to change as described therein. By accessing, using, and providing information to or through the Services, you acknowledge that you have reviewed and accepted our Privacy Policy, and you consent to all actions taken by us with respect to your information in compliance with the then-current version of our Privacy Policy.</p>
                </div>

                <div class="legal-section">
                    <h2>9. Intellectual Property Ownership; Feedback.</h2>
                    <p>(a) Provider IP. Customer acknowledges and agrees that the Services and Documentation are licensed, not sold, to Customer by Provider and, as between Customer and Provider, Provider owns all right, title, and interest, including all intellectual property rights, in and to the Provider IP, including Aggregated Statistics.</p>
                    <p>(b) Customer Data. Provider acknowledges that, as between Provider and Customer, Customer owns all right, title, and interest, including all intellectual property rights, in and to, other than Aggregated Statistics, information, data, and other content, in any form or medium, that is submitted, posted, or otherwise transmitted by or on behalf of Customer or an Authorized User through the Services (“Customer Data”). Customer hereby irrevocably grants all such rights and permissions in or relating to Customer Data as are necessary or useful to Provider and its representatives to enforce this Agreement and exercise Provider’s and its representatives rights and perform Provider’s and its representatives obligations hereunder. Customer will ensure that Customer Data and any Authorized User’s use of Customer Data will not violate any policy or terms referenced in or incorporated into this Agreement or any applicable law. Customer is solely responsible for the development, content, operation, maintenance, and use of Customer Data.</p>
                    <p>(c) Aggregated Statistics. Notwithstanding anything to the contrary in this Agreement, Provider may monitor Customer’s use of the Services and collect and compile data and information related to Customer’s use of the Services that is used by Provider in an aggregate and anonymized manner, including to compile statistical and performance information related to the provision and operation of the Services (“Aggregated Statistics”). As between Provider and Customer, all right, title, and interest in Aggregated Statistics, and all intellectual property rights therein, belong to and are retained solely by Provider. Customer acknowledges that Provider may compile Aggregated Statistics based on Customer Data input into the Services. Customer agrees that Provider may (i) make Aggregated Statistics publicly available in compliance with applicable law, and (ii) use Aggregated Statistics to the extent and in the manner permitted under applicable law; provided that such Aggregated Statistics do not identify Customer.</p>
                    <p>(d) Feedback. If Customer or any of its employees or contractors sends or transmits any communications or materials to Provider by mail, email, telephone, or otherwise, suggesting or recommending changes to the Provider IP, including without limitation, new features or functionality relating thereto, or any comments, questions, suggestions, or the like (“Feedback”), Provider is free to use such Feedback irrespective of any other obligation or limitation between the Parties governing such Feedback. All Feedback is and will be treated as non-confidential. Customer hereby assigns to Provider on Customer’s behalf, and on behalf of its employees, contractors, and/or agents, all right, title, and interest in, and Provider is free to use, without any attribution or compensation to Customer or any of its employees, contractors, and/or agents, any ideas, know-how, concepts, techniques, or other intellectual property rights contained in the Feedback, for any purpose whatsoever, although Provider is not required to use any Feedback.</p>
                </div>

                <div class="legal-section">
                    <h2>10. Disclaimer of Warranties.</h2>
                    <p>THE PROVIDER IP IS PROVIDED “AS IS” AND PROVIDER HEREBY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. PROVIDER SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT, AND ALL WARRANTIES ARISING FROM COURSE OF DEALING, USAGE, OR TRADE PRACTICE. PROVIDER MAKES NO WARRANTY OF ANY KIND THAT THE PROVIDER IP, OR ANY PRODUCTS OR RESULTS OF THE USE THEREOF, WILL MEET CUSTOMER’S OR ANY OTHER PERSON’S REQUIREMENTS, OPERATE WITHOUT INTERRUPTION, ACHIEVE ANY INTENDED RESULT, BE COMPATIBLE OR WORK WITH ANY SOFTWARE, SYSTEM, OR OTHER SERVICES, OR BE SECURE, ACCURATE, COMPLETE, FREE OF HARMFUL CODE, OR ERROR FREE OR THAT ANY ERRORS OR DEFECTS CAN OR WILL BE CORRECTED.</p>
                </div>

                <div class="legal-section">
                    <h2>11. Indemnification.</h2>
                    <p>(a) Customer shall indemnify, hold harmless, and, at Provider’s option, defend Provider from and against any losses, damages, liabilities, or costs (including reasonable attorneys’ fees) resulting from any third-party claim, suit, action, or proceeding (“Third-Party Claim”) alleging that the Customer Data, or any use of the Customer Data, infringes or misappropriates such third-party’s intellectual property rights and any Third-Party Claims based on Customer’s or any Authorized User’s (i) modifications of the Services or Documentation by anyone other than Provider; (ii) use of the Services and Documentation other than in accordance with the terms of this Agreement or in accordance with Provider’s instructions; (iii) use of the Services or Documentation in combination with other computer hardware or software not specified by Provider; (iv) failure to timely implement any modifications, upgrades, replacements, or enhancements made available to Customer by or on behalf of Provider; (v) third-party materials or Customer Data; or (vi) negligence or willful misconduct. In the event Provider seeks indemnification or defense from Customer under this provision, Provider shall promptly notify Customer in writing of the claim(s) brought against Provider for which Provider seeks indemnification or defense. Provider reserves the right, at its option and in its sole discretion, to assume full control of the defense of claims with legal counsel of Provider’s choice. Customer may not enter into any third-party agreement which would, in any manner whatsoever, affect Provider’s rights, constitute an admission of fault by Provider, or bind Provider in any manner, without Provider’s prior written consent.</p>
                    <p>(b) Provider shall indemnify and hold Customer harmless from and against any losses, damages, liabilities, or costs (including reasonable attorneys’ fees) resulting from any third-party claim, of copyright, patent or trademark infringement under US law, resulting from Customer’s use of the Services or Documentation, in compliance with the terms and conditions of this Agreement; provided that Customer promptly notifies Provider in writing of the Third-Party Claim, cooperates with Provider, and allows Provider sole authority to control the defense and settlement of such Third-Party Claim. Provider shall conduct such defense, at its sole expense, with attorneys selected by Provider, and shall have sole control over the conduct of such defense and all settlement negotiations on behalf of Customer and Provider. If such a Third-Party Claim is made or Provider anticipates such a Third-Party Claim will be made, Customer agrees to permit Provider, at Provider’s sole discretion, to (i) modify or replace the Services, or component or part thereof, to make it non-infringing, or (ii) obtain the right for Customer to continue use. If Provider determines that neither alternative is reasonably available, Provider may terminate this Agreement, in its entirety or with respect to the affected component or part, effective immediately on written notice to Customer. This Section 12(b) sets forth Customer’s sole remedies and Provider’s sole liability and obligation for any actual, threatened, or alleged Third-Party Claims that the Services infringe, misappropriate, or otherwise violate any intellectual property rights of any third party. Provider shall not have any liability or indemnification obligation under this Section if a claim of infringement is based in whole or in part, on (A) modifications of the Services or Documentation by anyone other than Provider; (B) use of the Services and Documentation other than in accordance with the terms of this Agreement or in accordance with Provider’s instructions; (C) use of the Services or Documentation in combination with other computer hardware or software not specified by Provider; (D) failure to timely implement any modifications, upgrades, replacements, or enhancements made available to Customer by or on behalf of Provider; (E) third-party materials or Customer Data; or (F) any knowing or reckless participation in infringing activities by Customer or any third-party acting on Customer’s behalf.</p>
                </div>

                <div class="legal-section">
                    <h2>12. Limitations of Liability.</h2>
                    <p>IN NO EVENT WILL PROVIDER BE LIABLE UNDER OR IN CONNECTION WITH THIS AGREEMENT UNDER ANY LEGAL OR EQUITABLE THEORY, INCLUDING BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, FOR ANY: (a) CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, ENHANCED, OR PUNITIVE DAMAGES; (b) INCREASED COSTS, DIMINUTION IN VALUE OR LOST BUSINESS, PRODUCTION, REVENUES, OR PROFITS; (c) LOSS OF GOODWILL OR REPUTATION; (d) USE, INABILITY TO USE, LOSS, INTERRUPTION, DELAY OR RECOVERY OF ANY DATA, OR BREACH OF DATA OR SYSTEM SECURITY; OR (e) COST OF REPLACEMENT GOODS OR SERVICES, IN EACH CASE REGARDLESS OF WHETHER PROVIDER WAS ADVISED OF THE POSSIBILITY OF SUCH LOSSES OR DAMAGES OR SUCH LOSSES OR DAMAGES WERE OTHERWISE FORESEEABLE. IN NO EVENT WILL PROVIDER’S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT UNDER ANY LEGAL OR EQUITABLE THEORY, INCLUDING BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, AND OTHERWISE EXCEED THE FEES PAID TO PROVIDER HEREUNDER IN THE TWELVE-MONTH PERIOD ENDING ON THE DATE THAT A CLAIM OR DEMAND IS FIRST ASSERTED.</p>
                </div>

                <div class="legal-section">
                    <h2>13. Term and Termination.</h2>
                    <p>(a) Term. The initial term of this Agreement begins on the Effective Date and, unless terminated earlier pursuant to this Agreement’s express provisions, will continue in effect for the period of time specified in the Order Form (the “Initial Term”). This Agreement will automatically renew for successive periods of time as specified in the Order Form (each a “Renewal Term” and together with the Initial Term, “the “Term”) unless earlier terminated pursuant to this Agreement’s express provisions or either Party gives the other Party written notice of non-renewal at least 60 days prior to the expiration of the then-current term (“Notice of Non-Renewal”).</p>
                    <p>(b) Termination. In addition to any other express termination right set forth in this Agreement: (i) Provider may terminate this Agreement for convenience, for any reason or no reason, upon 90 days prior written notice to Customer. (ii) Either Party may terminate this Agreement, effective on written notice to the other Party, if the other Party materially breaches this Agreement, and such breach: (A) is incapable of cure; or (B) being capable of cure, remains uncured 30 days after the non-breaching Party provides the breaching Party with written notice of such breach. (iii) Either Party may terminate this Agreement, effective immediately upon written notice to the other Party, if the other Party: (A) becomes insolvent or is generally unable to pay, or fails to pay, its debts as they become due; (B) files or has filed against it, a petition for voluntary or involuntary bankruptcy or otherwise becomes subject, voluntarily or involuntarily, to any proceeding under any domestic or foreign bankruptcy or insolvency law; (C) makes or seeks to make a general assignment for the benefit of its creditors; or (D) applies for or has appointed a receiver, trustee, custodian, or similar agent appointed by order of any court of competent jurisdiction to take charge of or sell any material portion of its property or business.</p>
                    <p>(c) Effect of Expiration or Termination. Upon expiration or earlier termination of this Agreement, Customer shall immediately discontinue use of the Provider IP and, without limiting Customer’s obligations under Section 8, Customer shall delete, destroy, or return all copies of the Provider IP. No expiration or termination will affect Customer’s obligation to pay all Fees that may have become due before such expiration or termination or entitle Customer to any refund. If Customer requests in writing at least 45 days prior to the effective date of expiration or termination, Provider will, within 45 days following such expiration or termination, deliver to Customer the then most recent version of Customer Data that is accessible by Provider, provided that Customer has at that time paid all fees and amounts then outstanding and any amounts payable after or as a result of such expiration or termination, including any expenses and fees, on a time and materials basis, for Provider’s services in transferring such Customer Data.</p>
                    <p>(d) Survival. This Section 14(d) and Section 1(b), Section 1(c), Section 7, Section 8, Section 9, Section 10, Section 11, Section 13, Section 14(c), and Section 15 survive any termination or expiration of this Agreement. No other provisions of this Agreement survive the expiration or earlier termination of this Agreement.</p>
                </div>

                <div class="legal-section">
                    <h2>14. Miscellaneous.</h2>
                    <p>(a) Entire Agreement. This Agreement, together with the Order Form, constitutes the sole and entire agreement of the Parties with respect to the subject matter of this Agreement and supersedes all prior and contemporaneous understandings, agreements, and representations and warranties, both written and oral, with respect to such subject matter. To the extent any conflict or inconsistency exists among the terms in the following documents, the order of precedence shall be (i) applicable Order Form, (ii) this Agreement, and (iii) the Documentation.</p>
                    <p>(b) Public Announcements. Neither Party shall issue or release any announcement, statement, press release, or other publicity or marketing materials relating to this Agreement or, unless expressly permitted under this Agreement, otherwise use the other Party’s trademarks, service marks, trade names, logos, domain names, or other indicia of source, association, or sponsorship, in each case, without the prior written consent of the other Party, which consent shall not be unreasonably withheld, provided, however, that Provider may, without Customer’s consent, include Customer’s name and other indicia in its lists of Provider’s current or former customers of Provider in promotional and marketing materials.</p>
                    <p>(c) Notices. All notices, requests, consents, claims, demands, waivers, and other communications hereunder (each, a “Notice”) must be in writing and addressed to Provider at the address set forth on the first page of this Agreement and to Customer at the address in the Order Form (or to such other address that may be designated by each respective Party from time to time in accordance with this Section). All Notices must be delivered by personal delivery, nationally recognized overnight courier (with all fees pre-paid), facsimile or email (with confirmation of transmission), or certified or registered mail (in each case, return receipt requested, postage pre-paid). Except as otherwise provided in this Agreement, a Notice is effective only: (i) upon receipt by the receiving Party; and (ii) if the Party giving the Notice has complied with the requirements of this Section. Notwithstanding the foregoing, Customer hereby consents to receiving electronic communications from Provider. These electronic communications may include notices about applicable fees and charges, transactional information, and other information concerning or related to the Services. Customer agrees that any notices, agreements, disclosures, or other communications that Provider sends to Customer electronically will satisfy any legal communication requirements, including that such communications be in writing.</p>
                    <p>(d) Modifications. Customer acknowledges and agrees that Provider has the right, in its sole discretion, to modify this Agreement from time to time, and that modified terms become effective on posting. Customer may be notified of modifications through notifications or posts on direct email communication. Customer is responsible for reviewing and becoming familiar with any such modifications. Customer’s continued use of the Services after the effective date of the modifications will be deemed acceptance of the modified terms.</p>
                    <p>(e) Waiver. No waiver by any Party of any of the provisions hereof shall be effective unless explicitly set forth in writing and signed by the Party so waiving. Except as otherwise set forth in this Agreement, no failure to exercise, or delay in exercising, any rights, remedy, power, or privilege arising from this Agreement will operate or be construed as a waiver thereof; nor shall any single or partial exercise of any right, remedy, power, or privilege hereunder preclude any other or further exercise thereof or the exercise of any other right, remedy, power, or privilege.</p>
                    <p>(f) Severability. If any provision of this Agreement is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability will not affect any other term or provision of this Agreement or invalidate or render unenforceable such term or provision in any other jurisdiction. Upon such determination that any term or other provision is invalid, illegal, or unenforceable, the Parties shall negotiate in good faith to modify this Agreement so as to effect their original intent as closely as possible in a mutually acceptable manner in order that the transactions contemplated hereby be consummated as originally contemplated to the greatest extent possible.</p>
                    <p>(g) Governing Law; Submission to Jurisdiction. This Agreement is governed by and construed in accordance with the internal laws of the Commonwealth of Pennsylvania without giving effect to any choice or conflict of law provision or rule that would require or permit the application of the laws of any jurisdiction other than those of the Commonwealth of Pennsylvania. Any legal suit, action, or proceeding arising out of or related to this Agreement or the licenses granted hereunder may be instituted in the federal courts of the United States or the courts of the Commonwealth of Pennsylvania in each case located in the city of Pittsburgh and County of Allegheny, and each Party irrevocably submits to the jurisdiction of such courts in any such suit, action, or proceeding.</p>
                    <p>(h) Assignment. Customer may not assign or transfer any of its rights or delegate any of its obligations hereunder, in each case whether voluntarily, involuntarily, by operation of law or otherwise, without the prior written consent of Provider. Any purported assignment, transfer, or delegation in violation of this Section is null and void.</p>
                    <p>(i) Export Regulation. Customer shall comply with all applicable federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), that prohibits or restricts the export or re-export of the Services or any Customer Data outside the US.</p>
                    <p>(j) Equitable Relief. Customer acknowledges and agrees that a breach or threatened breach by Customer of any of its obligations under Section 1(b), Section 8, or Section 10 would cause Provider irreparable harm for which monetary damages would not be an adequate remedy and agrees that, in the event of such breach or threatened breach, Provider will be entitled to equitable relief, including a restraining order, an injunction, specific performance, and any other relief that may be available from any court, without any requirement to post a bond or other security, or to prove actual damages or that monetary damages are not an adequate remedy. Such remedies are not exclusive and are in addition to all other remedies that may be available at law, in equity, or otherwise.</p>
                    <p>(k) Force Majeure. In no event will Provider be liable or responsible to Customer, or be deemed to have defaulted under or breached this Agreement, for any failure or delay in fulfilling or performing any term of this Agreement, when and to the extent such failure or delay is caused by any circumstances beyond Provider’s reasonable control (a “Force Majeure Event”), including (i) acts of God; (ii) flood, fire, earthquake, or explosion; (iii) war, invasion, hostilities (whether war is declared or not), terrorist threats or acts, riot or other civil unrest; (iv) government order, law, or actions; (v) embargoes or blockades in effect on or after the date of this Agreement; (vi) national or regional emergency; (vii) strikes, labor stoppages or slowdowns, or other industrial disturbances; and (viii) shortage of adequate power or transportation facilities. Either Party may terminate this Agreement if a Force Majeure Event continues substantially uninterrupted for a period of 30 days or more.</p>
                </div>
            </div>
        </div>
    </section>

</main>

<?php get_footer(); ?>